CREATE DATABASE CORPORATIVO
GO

USE CORPORATIVO
GO

--COMENTARIO
/*
COMENTARIO
EM 
BLOCO
*/
CREATE TABLE FUNCIONARIO (
	COD_FUNC INT NOT NULL PRIMARY KEY,
	NOME_FUNC VARCHAR(30)
)
GO

CREATE TABLE PECA (
	COD_PECA INT NOT NULL PRIMARY KEY,
	DESC_PECA VARCHAR(20)
)
GO

CREATE TABLE SETOR (
  COD_SETOR INT NOT NULL PRIMARY KEY,
  DESC_SETOR VARCHAR(20)
)
GO

CREATE TABLE CONTROLE_ESTOQUE (
  NR_CONTROLE INT NOT NULL PRIMARY KEY,
  [DATA] DATE,
  COD_FUNC_REPOSITOR INT,
  COD_FUNC_RESP INT,
  CONSTRAINT FK_CONTROLEESTOQUE_CODFUNCREPOSITOR
	FOREIGN KEY(COD_FUNC_REPOSITOR) REFERENCES
	  FUNCIONARIO(COD_FUNC),
  CONSTRAINT FK_CONTROLEESTOQUE_CODFUNCRESP
	FOREIGN KEY(COD_FUNC_RESP) REFERENCES
	  FUNCIONARIO(COD_FUNC)	
)
GO

CREATE TABLE ITENS_CONTROLE_EST (
  NR_CONTROLE INT NOT NULL,
  ITEM		  INT NOT NULL,
  COD_PECA	  INT,
  QTDE		  INT,
  TIPO_MOV	  CHAR(01),
  COD_SETOR	  INT,
  CONSTRAINT PK_ITENSCONTROLEEST PRIMARY KEY(NR_CONTROLE,ITEM),
  CONSTRAINT FK_ITENSCONTROLEEST_NRCONTROLE 
    FOREIGN KEY(NR_CONTROLE) 
	  REFERENCES CONTROLE_ESTOQUE (NR_CONTROLE),
  CONSTRAINT FK_ITENSCONTROLEEST_CODPECA 
    FOREIGN KEY(COD_PECA) REFERENCES PECA(COD_PECA),
  CONSTRAINT FK_ITENSCONTROLEEST_CODSETOR
    FOREIGN KEY(COD_SETOR) REFERENCES SETOR(COD_SETOR)
)
GO

